version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in...
  build:
    commands:
      - echo Build Docker Image
      - docker build -t myapp .
  post_build:
    commands:
      - echo Running Container
      - docker run -d -p 5000:5000 myapp
